language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
install:
  # Set up graphicsmagick
  - ./test/install.sh

  # Output graphicsmagick version
  - gm version

  # Install dependencies
  - npm install

notifications:
  email: false

